const productData = [
  {
    userReviews: [],
    title: "iPhone X",
    price: "899",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    rating: 4.44,
    brand: "Apple",
    category: "smartphones",
    image: "https://dummyjson.com/image/i/products/2/thumbnail.jpg",
    stock: 34,
    reviews: "22",
  },
  {
    userReviews: [],
    title: "OPPOF19",
    price: "280",
    description: "OPPO F19 is officially announced on April 2021.",
    rating: 4.3,
    brand: "OPPO",
    category: "smartphones",
    image: "https://dummyjson.com/image/i/products/4/thumbnail.jpg",
    stock: 123,
    reviews: "12",
  },
  {
    userReviews: [],
    title: "MacBook Pro",
    price: "1749",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    rating: 4.57,
    brand: "APPle",
    category: "laptops",
    image: "https://dummyjson.com/image/i/products/6/thumbnail.png",
    stock: 83,
    reviews: "22",
  },
  {
    userReviews: [],
    title: "Samsung Galaxy Book",
    price: "1499",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    rating: 4.25,
    brand: "Samsung",
    category: "laptops",
    image: "https://dummyjson.com/image/i/products/7/thumbnail.jpg",
    stock: 50,
    reviews: "5",
  },
  {
    userReviews: [],
    title: "Microsoft Surface Laptop 4",
    price: "1499",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    rating: 4.43,
    brand: "Microsoft Surface",
    category: "laptops",
    image: "https://dummyjson.com/image/i/products/8/thumbnail.jpg",
    stock: 68,
    reviews: "2",
  },
  {
    userReviews: [],
    title: "Infinix INBOOK",
    price: "1099",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    rating: 4.54,
    brand: "Infinix",
    category: "laptops",
    image: "https://dummyjson.com/image/i/products/9/thumbnail.jpg",
    stock: 96,
    reviews: "18",
  },
];

module.exports = productData;
